build: false
matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  global:
    APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2022'
    COLUMNS: 120  # Appveyor web viewer window width is 130 chars

  matrix:
   - PYTHON: "C:\\Python38"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install --upgrade setuptools 'pip<22'
  - pip install pytest-cov
  - pip install -e .[test_extra]
test_script:
  - pytest --color=yes -ra --cov --cov-report=xml
on_finish:
  - curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
  - codecov -e PYTHON_VERSION,PYTHON_ARCH
