name: ipython_docs
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.10
  - setuptools
  - sphinx>=4.2
  - sphinx_rtd_theme
  - numpy
  - exceptiongroup
  - testpath
  - matplotlib
  - pip
  - pip:
    - docrepr
    - prompt_toolkit
    - ipykernel
    - stack_data
    - -e ..
