name: ipython_docs
dependencies:
- python=3.8
- setuptools>=18.5
- sphinx>=1.8
- sphinx_rtd_theme
- numpy
- nose
- testpath
- matplotlib
- pip:
    - docrepr
    - prompt_toolkit
    - ipykernel
    - stack_data
