name: Run MyPy

on:
  push:
    branches: [ main, 7.x]
  pull_request:
    branches: [ main, 7.x]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pyflakes flake8 types-decorator
    - name: Lint with mypy
      run: |
        set -e
        mypy IPython
    - name: Lint with pyflakes
      run: |
        set -e
        flake8  IPython/core/magics/script.py
        flake8  IPython/core/magics/packaging.py
